name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: Bhacaz/checkout-files@v2
        with:
         files: thumbnail.png info.json LICENSE changelog.txt prototypes data-final-fixes.lua

      - name: Get version number
        run: |
          REGEX="(?<=Version: )([1-9]\.[0-9]\.[0-9])" 
          echo LATEST=$(grep -m 1 -oP "$REGEX" changelog.txt) >> $GITHUB_ENV

      - name: Make mod folder
        run: | 
          mkdir ./give-me-back-my-machine-gun-dammit
          mv $(ls --ignore=give-me-back-my-machine-gun-dammit) ./give-me-back-my-machine-gun-dammit

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: "give-me-back-my-machine-gun-dammit_${{env.LATEST}}"
          path: ${{github.workspace}}/*
          retention-days: 5

